"use strict";

const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const SUPPORTED_AGENTS = ["claude", "codex", "gemini", "omp", "ghost"];
const GENERATED_MARKER = "Generated by @ferdousbhai/slop-detector";

function shellQuote(value) {
  if (process.platform === "win32") return `"${value.replaceAll('"', '\\"')}"`;
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function invocation() {
  return {
    executable: process.execPath,
    args: [path.resolve(__dirname, "..", "bin", "slop-detector.js")],
  };
}

function hookCommand(runner) {
  const call = invocation();
  return [call.executable, ...call.args, "hook", runner].map(shellQuote).join(" ");
}

function readJson(filename) {
  if (!fs.existsSync(filename)) return {};
  try {
    return JSON.parse(fs.readFileSync(filename, "utf8"));
  } catch (error) {
    throw new Error(`Could not parse ${filename}: ${error.message}`);
  }
}

function writeFile(filename, content, options) {
  const previous = fs.existsSync(filename) ? fs.readFileSync(filename, "utf8") : null;
  if (previous === content) return { path: filename, changed: false };
  if (options.dryRun) return { path: filename, changed: true };

  fs.mkdirSync(path.dirname(filename), { recursive: true });
  if (previous !== null) {
    const backup = `${filename}.slop-detector.bak`;
    if (!fs.existsSync(backup)) fs.writeFileSync(backup, previous, { mode: 0o600 });
  }
  const temporary = `${filename}.slop-detector-${process.pid}.tmp`;
  fs.writeFileSync(temporary, content, { mode: 0o600 });
  fs.renameSync(temporary, filename);
  return { path: filename, changed: true };
}

function ownsHook(handler, runner) {
  return typeof handler?.command === "string"
    && handler.command.includes("slop-detector")
    && new RegExp(`[\\"']?hook[\\"']?\\s+[\\"']?${runner}(?=[\\"'\\s]|$)`).test(handler.command);
}

function installJsonHooks(filename, specs, options) {
  const settings = readJson(filename);
  const hooks = settings.hooks && typeof settings.hooks === "object" ? settings.hooks : {};
  const nextHooks = { ...hooks };

  for (const { eventName, runner } of specs) {
    const groups = Array.isArray(nextHooks[eventName]) ? nextHooks[eventName] : [];
    const cleaned = [];
    for (const group of groups) {
      if (!group || typeof group !== "object" || !Array.isArray(group.hooks)) {
        cleaned.push(group);
        continue;
      }
      const handlers = group.hooks.filter((handler) => !ownsHook(handler, runner));
      if (handlers.length > 0) cleaned.push({ ...group, hooks: handlers });
    }

    const promptHook = runner.endsWith("-prompt");
    cleaned.push({
      ...(runner === "gemini" ? { matcher: "*" } : {}),
      hooks: [{
        ...(runner === "gemini" ? { name: "slop-detector" } : {}),
        type: "command",
        command: hookCommand(runner),
        ...(runner === "gemini"
          ? { timeout: 5000 }
          : { timeout: 10, statusMessage: promptHook ? "Applying prior lint guidance" : "Linting final response" }),
      }],
    });
    nextHooks[eventName] = cleaned;
  }

  settings.hooks = nextHooks;
  return writeFile(filename, `${JSON.stringify(settings, null, 2)}\n`, options);
}

function enableCodexHooks(filename, options) {
  const original = fs.existsSync(filename) ? fs.readFileSync(filename, "utf8") : "";
  let next = original;
  const featureHeaders = [...next.matchAll(/^\[features\][ \t]*(?:#.*)?$/gm)];
  if (featureHeaders.length > 1) {
    throw new Error(`Refusing to edit ${filename}: multiple [features] tables`);
  }
  const section = featureHeaders[0];

  if (!section) {
    next = `${next.trimEnd()}${next.trim() ? "\n\n" : ""}[features]\nhooks = true\n`;
  } else {
    const sectionStart = section.index + section[0].length;
    const rest = next.slice(sectionStart);
    const nextSection = rest.search(/^\[[^\n]+\][ \t]*(?:#.*)?$/m);
    const sectionEnd = nextSection === -1 ? next.length : sectionStart + nextSection;
    const body = next.slice(sectionStart, sectionEnd);
    if (/^hooks\s*=\s*(?:true|false)(?:\s*#.*)?$/m.test(body)) {
      const updated = body.replace(/^hooks\s*=\s*(?:true|false)(\s*#.*)?$/m, "hooks = true$1");
      next = next.slice(0, sectionStart) + updated + next.slice(sectionEnd);
    } else {
      next = next.slice(0, sectionStart) + "\nhooks = true" + next.slice(sectionStart);
    }
  }

  return writeFile(filename, next, options);
}

function runtimeSource() {
  const call = invocation();
  const executable = JSON.stringify(call.executable);
  const baseArgs = JSON.stringify(call.args);
  const common = `// ${GENERATED_MARKER}. Do not edit; rerun slop-detector install-hooks.\nimport { spawn } from "node:child_process";\n\ntype HookResult = {\n  additionalContext?: string;\n  decision?: "block";\n  reason?: string;\n  systemMessage?: string;\n};\n\nconst executable = ${executable};\nconst baseArgs = ${baseArgs};\n\nfunction invoke(args: string[], input: unknown): Promise<HookResult> {\n  return new Promise((resolve, reject) => {\n    const child = spawn(executable, [...baseArgs, ...args], { stdio: ["pipe", "pipe", "pipe"] });\n    let stdout = "";\n    let stderr = "";\n    let failed = "";\n    const timer = setTimeout(() => {\n      failed = "Slop Detector timed out";\n      child.kill();\n    }, 10_000);\n    timer.unref();\n    child.stdout.setEncoding("utf8");\n    child.stderr.setEncoding("utf8");\n    child.stdout.on("data", (chunk) => {\n      stdout += chunk;\n      if (stdout.length > 2 * 1024 * 1024) {\n        failed = "Slop Detector output exceeded 2 MB";\n        child.kill();\n      }\n    });\n    child.stderr.on("data", (chunk) => { stderr += chunk; });\n    child.on("error", reject);\n    child.on("close", () => {\n      clearTimeout(timer);\n      if (failed) return reject(new Error(failed));\n      try { resolve(JSON.parse(stdout)); }\n      catch { reject(new Error(stderr.trim() || "Slop Detector returned invalid JSON")); }\n    });\n    child.stdin.on("error", () => {});\n    child.stdin.end(JSON.stringify(input));\n  });\n}\n`;

  return `${common}\nexport default function (pi) {\n  const sessionId = (ctx) => ctx.sessionManager.getSessionId();\n\n  pi.on("before_agent_start", async (event, ctx) => {\n    const result = await invoke(["hook", "omp-prompt"], {\n      session_id: sessionId(ctx),\n      prompt: event.prompt,\n    });\n    if (!result.additionalContext) return;\n    return {\n      message: {\n        customType: "slop-detector-warning-nudge",\n        content: result.additionalContext,\n        display: false,\n      },\n    };\n  });\n\n  pi.on("session_stop", async (event, ctx) => {\n    const result = await invoke(["hook", "omp"], {\n      session_id: sessionId(ctx),\n      last_assistant_message: event.last_assistant_message,\n      stop_hook_active: event.stop_hook_active,\n    });\n    if (result.systemMessage) ctx.ui.notify(result.systemMessage, "warning");\n    if (result.decision === "block" && result.reason) {\n      return { decision: "block", reason: result.reason };\n    }\n  });\n}\n`;
}

function installOwnedFile(filename, content, options) {
  if (fs.existsSync(filename)) {
    const current = fs.readFileSync(filename, "utf8");
    if (!current.includes(GENERATED_MARKER)) {
      throw new Error(`Refusing to overwrite non-Slop-Detector file: ${filename}`);
    }
  }
  return writeFile(filename, content, options);
}

function locations(scope, cwd) {
  const home = os.homedir();
  const configuredHome = process.env.XDG_CONFIG_HOME;
  const configHome = configuredHome && path.isAbsolute(configuredHome)
    ? configuredHome
    : path.join(home, ".config");
  if (scope === "project") {
    return {
      claude: path.join(cwd, ".claude", "settings.json"),
      codexHooks: path.join(cwd, ".codex", "hooks.json"),
      codexConfig: path.join(cwd, ".codex", "config.toml"),
      gemini: path.join(cwd, ".gemini", "settings.json"),
      omp: path.join(cwd, ".omp", "extensions", "slop-detector.ts"),
      ghost: path.join(cwd, ".ghost", "hooks.json"),
    };
  }
  return {
    claude: path.join(home, ".claude", "settings.json"),
    codexHooks: path.join(home, ".codex", "hooks.json"),
    codexConfig: path.join(home, ".codex", "config.toml"),
    gemini: path.join(home, ".gemini", "settings.json"),
    omp: path.join(process.env.PI_CODING_AGENT_DIR || path.join(home, ".omp", "agent"), "extensions", "slop-detector.ts"),
    ghost: path.join(configHome, "ghost", "hooks.json"),
  };
}

function installHooks(options = {}) {
  const scope = options.scope ?? "user";
  if (scope !== "user" && scope !== "project") throw new Error(`Invalid hook scope: ${scope}`);
  const requested = options.agents
    ?? (scope === "project" ? SUPPORTED_AGENTS.filter((agent) => agent !== "ghost") : SUPPORTED_AGENTS);
  for (const agent of requested) {
    if (!SUPPORTED_AGENTS.includes(agent)) throw new Error(`Unsupported agent: ${agent}`);
  }
  if (scope !== "user" && requested.includes("ghost")) {
    throw new Error("Ghost hooks are user-scoped; use --scope=user");
  }
  if (!options.dryRun) {
    installHooks({ ...options, agents: requested, dryRun: true });
  }

  const target = locations(scope, options.cwd ?? process.cwd());
  const results = [];
  for (const agent of requested) {
    if (agent === "claude") {
      results.push({ agent, ...installJsonHooks(target.claude, [
        { eventName: "Stop", runner: "claude" },
        { eventName: "UserPromptSubmit", runner: "claude-prompt" },
      ], options) });
    } else if (agent === "codex") {
      const config = enableCodexHooks(target.codexConfig, options);
      const hook = installJsonHooks(target.codexHooks, [
        { eventName: "Stop", runner: "codex" },
        { eventName: "UserPromptSubmit", runner: "codex-prompt" },
      ], options);
      results.push({ agent, path: hook.path, changed: config.changed || hook.changed, extraPaths: [config.path] });
    } else if (agent === "gemini") {
      results.push({ agent, ...installJsonHooks(target.gemini, [{ eventName: "AfterAgent", runner: "gemini" }], options) });
    } else if (agent === "omp") results.push({ agent, ...installOwnedFile(target.omp, runtimeSource(), options) });
    else if (agent === "ghost") {
      results.push({ agent, ...installJsonHooks(target.ghost, [
        { eventName: "session_stop", runner: "ghost" },
        { eventName: "before_prompt", runner: "ghost-prompt" },
      ], options) });
    }
  }
  return results;
}

module.exports = { GENERATED_MARKER, SUPPORTED_AGENTS, installHooks, locations };
